/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet.pkgfinal;

/**
 *
 * @author namre
 */
public class FenetredeJeu extends javax.swing.JFrame {
    Grille grillejeu = new Grille();
 
    /**
     * Creates new form FenetredeJeu
     */
    public FenetredeJeu() {
        initComponents();
        
        for (int i=4; i>=0; i--){
            for (int j=0; j<7; j++){
            CelluleGraphique cellgraph = new CelluleGraphique(grillejeu.Cellules[i][j]);
            grille_jeu.add(cellgraph);
        }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grille_jeu = new javax.swing.JPanel();
        joueur = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nom_joueur = new javax.swing.JTextField();
        score = new javax.swing.JPanel();
        message = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        chrono = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        grille_jeu.setBackground(new java.awt.Color(51, 204, 255));
        grille_jeu.setLayout(new java.awt.GridLayout(5, 7));
        getContentPane().add(grille_jeu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1064, 760));

        joueur.setBackground(new java.awt.Color(153, 153, 255));
        joueur.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        joueur.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("Nom Joueur :");
        joueur.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 80, 20));
        joueur.add(nom_joueur, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 110, -1));

        getContentPane().add(joueur, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 30, 220, 100));

        score.setBackground(new java.awt.Color(204, 102, 255));
        score.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        message.setViewportView(jTextArea1);

        score.add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 50, 170, -1));

        getContentPane().add(score, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 380, 220, 160));

        chrono.setBackground(new java.awt.Color(204, 204, 255));
        chrono.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(chrono, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 210, 220, 90));

        setBounds(0, 0, 1361, 1065);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetredeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetredeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetredeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetredeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetredeJeu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel chrono;
    private javax.swing.JPanel grille_jeu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel joueur;
    private javax.swing.JScrollPane message;
    private javax.swing.JTextField nom_joueur;
    private javax.swing.JPanel score;
    // End of variables declaration//GEN-END:variables
}
